import { css } from "@emotion/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Suspense } from "react";
import { useGetRepo2Query } from "../src/generated/graphql";

const Home: NextPage = () => {
  const { data, error } = useGetRepo2Query();

  if (error) {
    console.log(error);
    return <>error</>;
  }

  return (
    <Suspense fallback={<>loading...</>}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        css={css`
          background-color: red;
        `}
      >
        <div>
          <div>{data?.repository?.nameWithOwner}</div>
          <div>{data?.repository?.stargazerCount}</div>
        </div>
      </main>
    </Suspense>
  );
};

export default Home;
