import { css } from "@emotion/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useGetStarQuery } from "../src/generated/graphql";

const Home: NextPage = () => {
  const test = useGetStarQuery();
  console.log({ test });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1
          css={css`
            background-color: red;
          `}
        >
          test
        </h1>
      </main>
    </div>
  );
};

export default Home;
